spring.datasource.url=jdbc:h2:mem:invdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8081
spring.ai.openai.api-key=none

